spring:
  profiles: default
  application:
    name: bkAdmin
#spring.security.user.name=user
#spring.security.user.password=password
  security: 
    user: 
      name: user
      password: password
#spring.jmx.default-domain=admin
  jmx:
    default-domain: admin
  cloud:
#    config:
#      discovery:
#        enabled: true
#        serviceId: configserver
    gateway:
      discovery:
        locator:
          enabled: true
        routes:
         - id: default_path_to_http
          uri: https://windmt.com
          order: 10000 #网关服务监听 10000 端口
          predicates:
            - Path=/**
          filters:
            - SetPath=/
         - id: CompositeDiscoveryClient_CONSUMER
    uri: lb://CONSUMER
    order: 0
    predicates:
      - Path=/CONSUMER/**
    filters:
      - RewritePath=/CONSUMER/(?<segment>.*), /$\{segment}
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0 # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
  zipkin:
    base-url: http://172.16.16.56:9411/ # 指定了 Zipkin 服务器的地址
#server.servlet.context-path=/admin#配置上下文路径
server:
  servlet:
    context-path: /admin
server:
  port: 8007
#  context-path: /testProducer
feign:
  hystrix:
    enabled: true
management:
  endpoints:
#management.endpoint.health.show-details=always #health endpoint是否必须显示全部细节。默认情况下, /actuator/health 是公开的，并且不显示细节
    health: 
      show-details: always
    web:
      exposure:
        include: "*"
eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 3
    lease-renewal-interval-in-seconds: 10 #表示eureka client发送心跳给server端的频率
    health-check-url-path: /admin/actuator/health
  client:
    registryFetchIntervalSeconds: 5
#    healthcheck:
#      enabled: true
    serviceUrl: 
#      defaultZone: http://bkEureka56:8000/eureka/,http://bkEureka57:8000/eureka/,http://bkEureka58:8000/eureka/
#      defaultZone: http://172.16.16.56:8000/eureka/,http://172.16.16.57:8000/eureka/,http://172.16.16.58:8000/eureka/
      defaultZone: http://127.0.0.1:8000/eureka/

#为监控端点加前缀，这样才可以收集到监控信息
#eureka.instance.metadata-map.management.context-path=/admin/actuator
#eureka.instance.health-check-url=http://localhost:${server.port}/admin/actuator/health
#eureka.instance.status-page-url=http://localhost:${server.port}/admin/actuator/info
#eureka.instance.home-page-url=http://localhost:${server.port}
##eureka.instance.lease-renewal-interval-in-seconds=10
##eureka.instance.health-check-url-path=/admin/actuator/health
##eureka.client.registry-fetch-interval-seconds=5


