spring:
  profiles: default
  application:
    name: testProducer
  cloud:
    bus:
      trace:
        enabled: true
      enabled: true
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0 # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
  zipkin:
    base-url: http://172.16.16.56:9411/ # 指定了 Zipkin 服务器的地址
  boot:
    admin:
      client:
        url: http://localhost:8008
#----------------------------------------------------------------------------
  redis:
    # Redis数据库索引（默认为0）
    database: 10
    # Redis服务器地址
    host: 172.16.16.171
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 200
        # 连接池中的最大空闲连接
        max-idle: 20
        # 连接池中的最小空闲连接
        min-idle: 10
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
    timeout: 2000ms # 连接超时时间（毫秒）默认是2000ms
# Redis数据库索引（默认为0）
#spring.redis.database=1
# Redis服务器地址
#spring.redis.host=127.0.0.1
# Redis服务器连接端口
#spring.redis.port=6379
# Redis服务器连接密码（默认为空）
#spring.redis.password=
# 连接池最大连接数（使用负值表示没有限制）
#spring.redis.pool.max-active=1000
# 连接池最大阻塞等待时间（使用负值表示没有限制）
#spring.redis.pool.max-wait=-1
# 连接池中的最大空闲连接
#spring.redis.pool.max-idle=10
# 连接池中的最小空闲连接
#spring.redis.pool.min-idle=2
# 连接超时时间（毫秒）
#spring.redis.timeout=0
#-----------------------------------------------------------------------------
server:
  port: 8001
#  context-path: /testProducer
feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*" 
        #hystrix.stream,bus-refresh
  endpoint:
    health:
      show-details: ALWAYS
#eureka:
#  instance:
#    preferIpAddress: true
#    leaseRenewalIntervalInSeconds: 3
#  client:
#    registryFetchIntervalSeconds: 5
#    healthcheck:
#      enabled: true
#    serviceUrl: 
#      defaultZone: http://bkEureka56:8000/eureka/,http://bkEureka57:8000/eureka/,http://bkEureka58:8000/eureka/
#      defaultZone: http://172.16.16.56:8000/eureka/,http://172.16.16.57:8000/eureka/,http://172.16.16.58:8000/eureka/
#      defaultZone: http://127.0.0.1:8000/eureka/
swagger2: 
  title: 模块producer文档
  version: 1.0
  description: 模块producer文档描述
  basePackage: 
    - com.bk

tt: default016
configTestStr1: default016
info:
    profile: default007
    
---
spring: 
  application:
    name: testProducer
  profiles: dev
server:
  port: 8001
---
spring: 
  application:
    name: testProducer
  profiles: prod
server:
  port: 8001