#info.app.name=amber-cloud-dept-8001
#info.company.name=www.amber.com
#info.build.artifactId=$project.artifactId$
#info.build.version=$project.version$
info:
  app:
    name: "bk_configServer"
    encoding: 'UTF-8'
    java:
      source: '1.8.0_45'
      target: '1.8.0_45'
#  company:
#    name: bkLto
  build:
    name: "bk_configServer"
    groupId: "com.bk"
    artifactId: "bk_configServer"
    version: "0.0.1-SNAPSHOT"
    
spring:
  profiles: default
  application:
    name: bkConfigServer
  cloud:
#    config:
#      discovery:
#        enabled: true
#        serviceId: configserver
    config:
      server:
        git:
          uri: http://172.16.16.90:8000/r/~test1/springCloundCfg/funo/cfg.git
          search-paths: /config-repo,/test_producer
          username: test1
          password: test1
#spring.cloud.config.server.git.username：访问 Git 仓库的用户名
#spring.cloud.config.server.git.password：访问 Git 仓库的用户密码
    bus:
      enabled: true
      trace:
        enabled: true
    stream:
#      bindings:
        #配置自己定义的通道与哪个中间件交互
#        shop_input: #ShopChannel里Input和Output的值
#          destination: springConfigServerShopInput #目标主题
#        shop_output:
#          destination: springConfigServerShopOutput
#      default-binder: kafka #默认的binder是kafka
      kafka:
        binder:
          # Kafka的服务端列表，默认localhost
          brokers: 172.16.16.90:9092
          # Kafka服务端连接的ZooKeeper节点列表，默认localhost
          zkNodes: 172.16.16.90:2181
          minPartitionCount: 1
          autoCreateTopics: true
          autoAddPartitions: true
server:
  port: 8005
#  context-path: /testProducer
feign:
  hystrix:
    enabled: true
management: #监控短点配置
  security:
    enabled: false
  #是否需要权限拉去，默认是true,如果不false就不允许你去拉取配置中心Server更新的内容
  endpoints:
    actuator:
      enabled: true
    shutdown:
      enabled: true
    web:
      exposure:
#        include: bus-refresh,hystrix.stream
        include: "*" #暴露所有端点 默认是info,health
#management.endpoints.web.exposure.include=*
eureka:
  instance:
    preferIpAddress: true
#    leaseRenewalIntervalInSeconds: 3
  client:
#    registryFetchIntervalSeconds: 5
#    healthcheck:
#      enabled: true
    serviceUrl: 
#      defaultZone: http://bkEureka56:8000/eureka/,http://bkEureka57:8000/eureka/,http://bkEureka58:8000/eureka/
      defaultZone: http://172.16.16.56:8000/eureka/,http://172.16.16.57:8000/eureka/,http://172.16.16.58:8000/eureka/
#      defaultZone: http://127.0.0.1:8000/eureka/
swagger2: 
  title: 配置中心文档
  version: 1.0
  description: 配置中心文档描述
  basePackage: 
    - com.bk
---
spring: 
  application:
    name: bkConfigServer
  profiles: dev
server:
  port: 8005
---
spring: 
  application:
    name: bkConfigServer
  profiles: prod
server:
  port: 8005