server:
  port: 8006
spring:
  profiles: default
  application:
    name: bkZull
  zipkin:
    base-url: http://172.16.16.56:9411/
  boot:
    admin:
      client:
        url: http://172.16.16.58:8008
feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*" 
  endpoint:
    health: 
      show-details: always
---
spring: 
  application:
    name: bkZull
  profiles: dev
server:
  port: 8006
---
spring: 
  application:
    name: bkZull
  profiles: prod
server:
  port: 8006