#info.app.name=amber-cloud-dept-8001
#info.company.name=www.amber.com
#info.build.artifactId=$project.artifactId$
#info.build.version=$project.version$
info:
  app:
    name: "@project.artifactId@"
    encoding: '@project.build.sourceEncoding@'
    java:
      source: '@java.version@'
      target: '@java.version@'
#  company:
#    name: bkLto
  build:
    name: "@project.artifactId@"
    groupId: "@project.groupId@"
    artifactId: "@project.artifactId@"
    version: "@project.version@"
    
spring:
  profiles: default
  application:
    name: bkConfigServer
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://172.16.16.56:9411
  cloud:
#    config:
#      discovery:
#        enabled: true
#        serviceId: configserver
    config:
      server:
        git:
          uri: http://172.16.16.90:8000/r/~test1/springCloundCfg/funo/cfg.git
          search-paths: /config-repo,/test_producer
          username: test1
          password: test1
#spring.cloud.config.server.git.username：访问 Git 仓库的用户名
#spring.cloud.config.server.git.password：访问 Git 仓库的用户密码
    bus:
      enabled: true
      trace:
        enabled: true
      refresh:
        enabled: true
  kafka:
    bootstrap-servers: 172.16.16.90:9092
    consumer:
      group-id: test
#spring.kafka.bootstrap-servers=localhost:9092
#spring.kafka.consumer.group-id=test
#spring.cloud.bus.refresh.enabled=true

server:
  port: 8005
#  context-path: /testProducer
feign:
  hystrix:
    enabled: true
management: #监控短点配置
#  security:
#    enabled: false
  #是否需要权限拉去，默认是true,如果不false就不允许你去拉取配置中心Server更新的内容
  endpoints:
#    actuator:
#      enabled: true
#    shutdown:
#      enabled: true
    web:
      exposure:
#        include: bus-refresh,hystrix.stream
        include: "*"
        #暴露所有端点 默认是info,health
#management.endpoints.web.exposure.include=*
eureka:
  instance:
 #   status-page-url: http://${spring.cloud.client.ipAddress}:${server.port}/swagger-ui.html 
#    preferIpAddress: true
    prefer-ip-address: true
#    leaseRenewalIntervalInSeconds: 3
    lease-renewal-interval-in-seconds: 5 #Eureka客户端向服务端发送心跳的时间间隔，单位为秒（客户端告诉服务端自己会按照该规则），默认30
    lease-expiration-duration-in-seconds: 7 #Eureka服务端在收到最后一次心跳之后等待的时间上限，单位为秒，超过则剔除（客户端告诉服务端按照此规则等待自己），默认90
  client:
    registry-fetch-interval-seconds: 5 #eureka client刷新本地缓存时间，默认30
#    healthcheck:
#      enabled: true
    serviceUrl: 
#      defaultZone: http://bkEureka56:8000/eureka/,http://bkEureka57:8000/eureka/,http://bkEureka58:8000/eureka/
#      defaultZone: http://172.16.16.56:8000/eureka/,http://172.16.16.57:8000/eureka/,http://172.16.16.58:8000/eureka/
      defaultZone: http://127.0.0.1:8000/eureka/
swagger2: 
  title: 配置中心文档
  version: 1.0
  description: 配置中心文档描述
  basePackage: 
    - com.bk
---
spring: 
  application:
    name: bkConfigServer
  profiles: dev
server:
  port: 8005
---
spring: 
  application:
    name: bkConfigServer
  profiles: prod
server:
  port: 8005